Timeout Minute and Continue on Error added

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,27 +1,45 @@
-# Configuration variables(CV) are availables for all workflow under a REPO.
-# Or Multiple REPO of under an organization(ORG).
-# We never define CV in workflow files. We define in ORG/REPO/ENV level
+# timeout-minutes: 1 - Give timeout to execute an step in minute. This can be used in Job Level also.
+# continue-on-error: true - Prevent the entire job failing, if current step fail
 
-name: Configuration Variables & Secret
+name: Status Check Function
 on: [push]
 jobs:
-  log-vars:
-    # ${{ vars }} This OBJ will have all ORG/REPO/ENV Varialbes
-    runs-on: ${{ vars.JOBS_RUNNER }}
-    environment: "production"
-    env:
-      # Make ORG/REPO/ENV level secrets as local env.
-      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
-      # Make ORG/REPO/ENV level variables as local env.
-      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
-      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
+  job-1:
+    runs-on: ubuntu-latest
     steps:
-      - name: Run only if BOOLEAN_SECRET is true
-        if: env.BOOLEAN_SECRET == 'true'
-        run: echo "I ran"
-      
-      - name: Log Vars
-        run: |
-          echo '${{ vars.JOBS_RUNNER }}'
-          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
-          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
+      - name: Step 1
+        run: sleep 90
+        # Very Imp. Give timeout to execute an step in minute. This can be used in Job Level also.
+        timeout-minutes: 1
+      - name: Step 2
+        id: step-2
+        # Very Imp. Below line will prevent the entire job failing, if step-2 fail
+        continue-on-error: true
+        run: exit 1
+      - name: Runs on Specific Failure
+        # If step with id 'step-2' fails then only below step will execute.
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
+      - name: Runs on every Failure
+        # 'failure()' returns 'true' when any previous step of job fails.
+        if: failure()
+        run: echo 'Runs only on failure'
+      - name: Runs on Success
+        # This is not needed, as 'success' is default behaviour.
+        # 'success()' is applied bydefault to every 'if' statement unless you override it's behaviour. 
+        if: success()
+        run: echo 'Runs on Success'
+      - name: Always Runs
+        # if : success() || failure() # This is same as below.
+        if: always()
+        run: echo 'Always Run'
+      - name: Runs when cancelled
+        if: cancelled()
+        run: echo 'Runs on Cancelled'
+  
+  job-2:
+    runs-on: ubuntu-latest
+    needs: job-1
+    if: failure()
+    steps:
+      - run: echo 'Job 2'
